# Generated by Django 5.0.3 on 2024-03-22 02:44

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='inventory',
            managers=[
                ('inventory_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.DeleteModel(
            name='StockReport',
        ),
    ]
