# Generated by Django 5.0.3 on 2024-03-19 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='item_name',
        ),
        migrations.AddField(
            model_name='order',
            name='menu_item_name',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.item'),
        ),
    ]
