# Generated by Django 5.0.3 on 2024-03-23 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_item_name_inventory_ingredient_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='menu_item_name',
            new_name='order_item',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='quantity',
            new_name='order_quantity',
        ),
    ]
