# Generated by Django 5.0.3 on 2024-03-20 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_order_description_order_remark'),
        ('menu', '0002_menuitem_category_menuitem_receipe_receipe_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockreport',
            name='menu_item_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.menuitem'),
        ),
        migrations.AddField(
            model_name='stockreport',
            name='stock_remain',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stockreport',
            name='inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory'),
        ),
        migrations.AlterField(
            model_name='stockreport',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.order'),
        ),
    ]
