# Generated by Django 5.0.3 on 2024-03-20 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stockreport_menu_item_name_stockreport_stock_remain_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockreport',
            old_name='inventory',
            new_name='inventory_quantity',
        ),
        migrations.RenameField(
            model_name='stockreport',
            old_name='order',
            new_name='order_quantity',
        ),
    ]
