# Generated by Django 5.0.3 on 2024-03-18 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_order_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='table',
        ),
    ]
