# Generated by Django 5.0.3 on 2024-03-19 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_stockreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='item_name',
            field=models.CharField(max_length=100),
        ),
    ]
