# Generated by Django 5.0.3 on 2024-03-19 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_purchase_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
