# Generated by Django 5.0.3 on 2024-03-20 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipe',
            name='name',
            field=models.OneToOneField(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.ingredient'),
        ),
    ]
