# Generated by Django 5.0.3 on 2024-03-20 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='price',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='quantity',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='unit',
            field=models.FloatField(null=True),
        ),
    ]
