# Generated by Django 5.0.3 on 2024-03-19 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
                ('unit', models.CharField(choices=[('kg', 'kg'), ('gm', 'gm'), ('piece', 'piece'), ('ml', 'ml'), ('liter', 'liter')], max_length=100, null=True)),
                ('name', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.ingredient')),
            ],
        ),
    ]
