# Generated by Django 5.0.3 on 2024-03-20 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_remove_menuitem_description_remove_menuitem_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='unit',
            new_name='price',
        ),
    ]
