# Generated by Django 5.0.3 on 2024-03-22 02:44

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_receipe_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='menuitem',
            managers=[
                ('menu_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
