# Generated by Django 5.0.3 on 2024-03-20 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_rename_unit_menuitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='unit',
            field=models.CharField(choices=[('kg', 'kg'), ('gm', 'gm'), ('piece', 'piece'), ('ml', 'ml'), ('liter', 'liter')], max_length=100, null=True),
        ),
    ]
