# Generated by Django 5.0.3 on 2024-03-19 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='receipe',
            field=models.ManyToManyField(to='menu.receipe'),
        ),
    ]
