# Generated by Django 5.0.3 on 2024-03-23 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_ingredient_quantity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Receipe',
            new_name='Recipe',
        ),
    ]
