# Generated by Django 5.0.3 on 2024-03-20 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_menuitem_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='unit',
        ),
    ]
