# Generated by Django 5.0.3 on 2024-03-20 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_remove_menuitem_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='quantity',
        ),
    ]
